"""empty message

Revision ID: 014974cc5bf6
Revises: 1b8fb1860d97
Create Date: 2021-04-21 23:59:58.669072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014974cc5bf6'
down_revision = '1b8fb1860d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd20_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True, comment='日期'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('task', sa.String(length=50), nullable=True, comment='服事項目'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sd20_tasks')
    # ### end Alembic commands ###
