"""empty message

Revision ID: 07462b86c3d9
Revises: 67e072ca92c4
Create Date: 2021-04-14 15:34:10.530545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07462b86c3d9'
down_revision = '67e072ca92c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd11_users', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='流水號',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd11_users', 'id',
               existing_type=postgresql.UUID(),
               comment='流水號',
               autoincrement=True)
    # ### end Alembic commands ###
