"""empty message

Revision ID: 20a8027f035f
Revises: e5800504fa8d
Create Date: 2021-05-03 15:32:27.075445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a8027f035f'
down_revision = 'e5800504fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd11_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_unique_id', sa.String(length=64), nullable=True, comment='使用者在Line上的unique ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名, 包括團體: ex: 青少契'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='暱稱'),
    sa.Column('access_token', sa.String(length=64), nullable=True, comment='用於Line Notify的Token'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='0=停用，1=啟用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('telephone', sa.String(length=30), nullable=True, comment='Telephone number'),
    sa.Column('line_id', sa.String(length=30), nullable=True, comment='LINE id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd20_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True, comment='日期'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('task', sa.String(length=50), nullable=True, comment='服事項目'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd21_Bible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('locate', sa.String(length=50), nullable=True, comment='經文位置'),
    sa.Column('sentence', sa.Text(), nullable=False, comment='經文內容'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sd21_Bible')
    op.drop_table('sd20_tasks')
    op.drop_table('sd11_users')
    # ### end Alembic commands ###
