"""empty message

Revision ID: 40f6180387cb
Revises: 51f45271e914
Create Date: 2021-04-14 15:25:10.829598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f6180387cb'
down_revision = '51f45271e914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sd11_users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='流水號'))
    # ### end Alembic commands ###
