"""empty message

Revision ID: 51f45271e914
Revises: dc0be4c8969c
Create Date: 2021-04-14 15:23:34.339793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51f45271e914'
down_revision = 'dc0be4c8969c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('temp_id', postgresql.UUID(as_uuid=True), nullable=True, comment='流水號'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sd11_users', 'temp_id')
    # ### end Alembic commands ###
