"""empty message

Revision ID: 59449abd0ddc
Revises: 07462b86c3d9
Create Date: 2021-04-14 15:35:30.527322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59449abd0ddc'
down_revision = '07462b86c3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sd11_users', 'id')
    # ### end Alembic commands ###
