"""empty message

Revision ID: 67e072ca92c4
Revises: 40f6180387cb
Create Date: 2021-04-14 15:25:34.519702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67e072ca92c4'
down_revision = '40f6180387cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='流水號'))
    op.drop_column('sd11_users', 'temp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('temp_id', postgresql.UUID(), autoincrement=False, nullable=True, comment='流水號'))
    op.drop_column('sd11_users', 'id')
    # ### end Alembic commands ###
