"""empty message

Revision ID: 7e77b10bec9e
Revises: be2dc022d87d
Create Date: 2021-04-14 15:42:42.256113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e77b10bec9e'
down_revision = 'be2dc022d87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd11_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_unique_id', sa.String(length=64), nullable=True, comment='使用者在Line上的unique ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='暱稱'),
    sa.Column('access_token', sa.String(length=64), nullable=True, comment='用於Line Notify的Token'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='0=停用，1=啟用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('telephone', sa.String(length=30), nullable=True, comment='Telephone number'),
    sa.Column('line_id', sa.String(length=30), nullable=True, comment='LINE id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sd11_users')
    # ### end Alembic commands ###
