"""empty message

Revision ID: 8f0dfa3a3cb5
Revises: 014974cc5bf6
Create Date: 2021-04-26 20:47:15.756161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0dfa3a3cb5'
down_revision = '014974cc5bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd11_users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='姓名, 包括團體: ex: 青少契',
               existing_comment='姓名',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd11_users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='姓名',
               existing_comment='姓名, 包括團體: ex: 青少契',
               existing_nullable=False)
    # ### end Alembic commands ###
