"""empty message

Revision ID: b7f18279ed4f
Revises: b76284256301
Create Date: 2021-04-14 14:58:58.933810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f18279ed4f'
down_revision = 'b76284256301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('access_token', sa.String(length=64), nullable=True, comment='用於Line Notify的Token'))
    op.alter_column('sd11_users', 'display_name',
               existing_type=sa.VARCHAR(length=50),
               comment='暱稱',
               existing_comment='Display name',
               existing_nullable=True)
    op.alter_column('sd11_users', 'id',
               existing_type=sa.INTEGER(),
               comment='使用者在Line上的unique ID',
               autoincrement=True)
    op.alter_column('sd11_users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='姓名',
               existing_comment='Name',
               existing_nullable=False)
    op.alter_column('sd11_users', 'status',
               existing_type=sa.INTEGER(),
               comment='0=停用，1=啟用',
               existing_comment='Status',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('sd11_users_cust_id_name_key', 'sd11_users', type_='unique')
    op.drop_constraint('sd11_users_cust_id_fkey', 'sd11_users', type_='foreignkey')
    op.drop_column('sd11_users', 'cust_id')
    op.drop_column('sd11_users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Password'))
    op.add_column('sd11_users', sa.Column('cust_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Customer id'))
    op.create_foreign_key('sd11_users_cust_id_fkey', 'sd11_users', 'sd10_customers', ['cust_id'], ['id'])
    op.create_unique_constraint('sd11_users_cust_id_name_key', 'sd11_users', ['cust_id', 'name'])
    op.alter_column('sd11_users', 'status',
               existing_type=sa.INTEGER(),
               comment='Status',
               existing_comment='0=停用，1=啟用',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd11_users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='Name',
               existing_comment='姓名',
               existing_nullable=False)
    op.alter_column('sd11_users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='使用者在Line上的unique ID',
               autoincrement=True)
    op.alter_column('sd11_users', 'display_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Display name',
               existing_comment='暱稱',
               existing_nullable=True)
    op.drop_column('sd11_users', 'access_token')
    # ### end Alembic commands ###
