"""empty message

Revision ID: be2dc022d87d
Revises: 59449abd0ddc
Create Date: 2021-04-14 15:39:30.647178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2dc022d87d'
down_revision = '59449abd0ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sd11_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sd11_users', 'id')
    # ### end Alembic commands ###
