"""empty message

Revision ID: de7ee29a3fe9
Revises: 7e77b10bec9e
Create Date: 2021-04-14 23:07:50.050587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7ee29a3fe9'
down_revision = '7e77b10bec9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd10_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='Status'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Vendor of customer'),
    sa.Column('issue_namespace', sa.String(length=50), server_default='CUSTOM-{datetime:%Y%m%d}-{serial_no:05d}', nullable=False, comment='Issue number namespace'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd10_customers_name'), 'sd10_customers', ['name'], unique=True)
    op.create_table('sd11_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_unique_id', sa.String(length=64), nullable=True, comment='使用者在Line上的unique ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='暱稱'),
    sa.Column('access_token', sa.String(length=64), nullable=True, comment='用於Line Notify的Token'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='0=停用，1=啟用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('telephone', sa.String(length=30), nullable=True, comment='Telephone number'),
    sa.Column('line_id', sa.String(length=30), nullable=True, comment='LINE id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd13_user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd19_status_privileges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='authorization role, ex: admin, user'),
    sa.Column('status_from', sa.Integer(), nullable=True, comment='Current state'),
    sa.Column('status_to', sa.Integer(), nullable=True, comment='Next state'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sd19_status_privileges')
    op.drop_table('sd13_user_groups')
    op.drop_table('sd11_users')
    op.drop_index(op.f('ix_sd10_customers_name'), table_name='sd10_customers')
    op.drop_table('sd10_customers')
    # ### end Alembic commands ###
