"""empty message

Revision ID: f8b14e768ae0
Revises: 8cc776249c95
Create Date: 2021-04-20 23:44:59.005802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b14e768ae0'
down_revision = '8cc776249c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd10_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='Status'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Vendor of customer'),
    sa.Column('issue_namespace', sa.String(length=50), server_default='CUSTOM-{datetime:%Y%m%d}-{serial_no:05d}', nullable=False, comment='Issue number namespace'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd10_customers_name'), 'sd10_customers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sd10_customers_name'), table_name='sd10_customers')
    op.drop_table('sd10_customers')
    # ### end Alembic commands ###
